
--This creates all the tables in the DATABASE 
-- and the necessary contraints 

create table Employee(
    employeeNo number generated by default as identity primary key,
    employeeFName varchar2(100) not null,
    employeeLName varchar2(100) not null,
    employeeEmail varchar2(300) not null,
    employeeContact varchar2(20) not null);

create table Client(
    clientNo number generated by default as identity primary key,
    clientName varchar2(100) not null,
    clientEmail varchar2(300) not null,
    clientContact varchar2(20) not null);

create table Delegate(
    delegateNo number generated by default as identity primary key,
    delegateTitle varchar2(50) not null,
    delegateFName varchar2(100) not null,
    delegateLName varchar2(100) not null,
    delegateStreet varchar2(50),
    delegateCity varchar2(50) not null,
    delegateState varchar2(50),
    delegateZipCode varchar2(50),
    attTelNo varchar2(20) not null,
    attFaxNo varchar2(20),
    attEmailAddress varchar2(300) not null,
    clientNo number,
    foreign key (clientNo) references Client(clientNo));

create table CourseType(
    courseTypeNo number generated by default as identity primary key,
    courseTypeDescription varchar2(50) not null);

create table Course(
    courseNo number generated by default as identity primary key,
    courseName varchar2(50) not null,
    courseDescription varchar2(50) not null,
    startDate date not null,
    startTime timestamp not null,
    endDate date not null,
    endTime timestamp not null,
    maxDelegates number not null,
    confirmed char(1) not null,
    delivererEmployeeNo number not null,
    courseTypeNo number not null,
    foreign key (delivererEmployeeNo) references Employee(employeeNo),
    foreign key (courseTypeNo) references CourseType(courseTypeNo));

create table CourseFee(
    courseFeeNo number generated by default as identity primary key,
    feeDescription varchar2(50) not null,
    fee number not null,
    courseNo number not null,
    foreign key (courseNo) references Course(courseNo));

create table PaymentMethod(
    pMethodNo number generated by default as identity primary key,
    pMethodName varchar2(100) not null);

create table Location(
    locationNo number generated by default as identity primary key,
    locationName varchar2(100) not null,
    locationMaxSize number not null);

create table Registration(
    registrationNo number generated by default as identity primary key,
    registrationDate date default trunc(sysdate) not null,
    delegateNo number not null,
    courseFeeNo number not null,
    registerEmployeeNo number not null,
    courseNo number not null,
    foreign key (delegateNo) references Delegate(delegateNo),
    foreign key (courseFeeNo) references CourseFee(courseFeeNo),
    foreign key (registerEmployeeNo) references Employee(employeeNo),
    foreign key (courseNo) references Course(courseNo));

create table Invoice(
    invoiceNo number generated by default as identity primary key,
    dateRaised date default trunc(sysdate) not null,
    datePaid date not null,
    creditCardNo number,
    holdersName varchar2(100),
    expiryDate date,
    registrationNo number  not null,
    pMethodNo number not null,
    foreign key (registrationNo) references Registration(registrationNo),
    foreign key (pMethodNo) references PaymentMethod(pMethodNo));

create table Booking(
    bookingNo number generated by default as identity primary key,
    bookingDate date default trunc(sysdate) not null,
    locationNo number not null,
    courseNo number not null,
    bookingEmployeeNo number not null,
    foreign key (locationNo) references Location(locationNo),
    foreign key (courseNo) references Course(courseNo),
    foreign key (bookingEmployeeNo) references Employee(employeeNo));

